import React, { useState, useEffect } from 'react';
import { StyleSheet, View, StatusBar, Alert } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { Navbar } from './src/components/Navbar';
import { HomePage } from './src/components/HomePage';
import { ChatBoxPage } from './src/components/ChatBoxPage';
import { TasksPage } from './src/components/TasksPage';
import { SettingsPage } from './src/components/SettingsPage';
import { LocationsPage } from './src/components/LocationsPage';
import { LinearGradient } from 'expo-linear-gradient';
import { NotificationListener } from './src/services/NotificationListener';
import { DevConsoleModal } from './src/components/DevConsoleModal';
import { ErrorBoundary } from './src/components/ErrorBoundary';
import { Terminal } from 'lucide-react-native';
import { TouchableOpacity } from 'react-native';
import { Task, SavedLocation } from './src/types';
import { TaskManager } from './src/services/TaskManager';
import { DevLogger } from './src/services/DevLogger';
import { syncTasksToCloud } from './src/services/CloudSync';
import { RNAndroidNotificationListenerHeadlessJsName } from 'react-native-android-notification-listener';

// Register the Headless Task for background notification listening

function AppContent() {
  const [currentPage, setCurrentPage] = useState<'home' | 'chat' | 'tasks' | 'settings' | 'locations'>('home');
  const [isDevConsoleOpen, setIsDevConsoleOpen] = useState(false);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [savedLocations, setSavedLocations] = useState<SavedLocation[]>([
    { id: '1', name: 'Home', address: 'Cluj-Napoca, Romania', latitude: 46.7712, longitude: 23.6236 },
    { id: '2', name: 'Work', address: 'Cluj Business Center', latitude: 46.7700, longitude: 23.5900 },
  ]);

  // Load tasks from local storage on mount
  useEffect(() => {
    const loadTasks = async () => {
      // First load local tasks
      let loadedTasks = await TaskManager.getTasks();
      
      // Then try to sync with cloud
      try {
        const cloudTasks = await TaskManager.syncWithCloud();
        if (cloudTasks.length > 0) {
          loadedTasks = cloudTasks;
        }
      } catch (e) {
        console.error('Initial cloud sync failed', e);
      }

      if (loadedTasks.length > 0) {
        setTasks(loadedTasks);
      } else {
        // Initial seed data if empty
        const initialTasks: Task[] = [
          { id: 1, title: 'Review meeting notes', description: 'From yesterday\'s team sync', completed: false, dueDate: 'Due in 2 days', date: 'Dec 8', category: 'Work', priority: 'High', source: 'Email' },
          { id: 2, title: 'Buy groceries', description: 'Milk, eggs, bread', completed: false, date: 'Dec 7', category: 'Personal', priority: 'Medium', source: 'Apps' },
          { id: 4, title: 'Read book chapter', description: 'Chapter 5 - Productivity', completed: false, dueDate: 'Due in 4 days', date: 'Dec 10', category: 'Personal', priority: 'Low', source: 'Apps' },
          { id: 5, title: 'Gym session', description: 'Leg day workout', completed: false, date: 'Dec 6', category: 'Social', priority: 'Medium', source: 'WhatsApp' },
          { id: 6, title: 'Pay bills', description: 'Monthly utilities payment', completed: false, date: 'Dec 9', category: 'Finance', priority: 'High', source: 'Email' },
        ];
        // Save initial tasks one by one to ensure IDs are generated correctly or just save them
        // For simplicity, we'll just set them in state and let the user save new ones.
        // Or better, let's save them to storage so they persist.
        for (const task of initialTasks) {
          // We need to cast to Omit<Task, 'id'> but we want to keep these specific IDs?
          // TaskManager generates IDs. Let's just use TaskManager.addTask for each.
          const { id, ...taskData } = task;
          await TaskManager.addTask(taskData);
        }
        setTasks(await TaskManager.getTasks());
      }
      
      // Sync with cloud
      const currentTasks = await TaskManager.getTasks();
      if (currentTasks.length > 0) {
        syncTasksToCloud(currentTasks).catch(err => console.error('Sync failed:', err));
      }
    };
    loadTasks();
  }, []);

  const toggleTask = async (id: number) => {
    const taskToUpdate = tasks.find(t => t.id === id);
    if (taskToUpdate) {
      const isCompleted = !taskToUpdate.completed;
      const updatedTask = { 
        ...taskToUpdate, 
        completed: isCompleted,
        completedAt: isCompleted ? new Date().toISOString() : undefined
      };
      setTasks(tasks.map(task => task.id === id ? updatedTask : task));
      await TaskManager.updateTask(updatedTask);
    }
  };

  const addTask = async (newTask: Task) => {
    // Remove the temporary ID generated by the modal
    const { id, ...taskData } = newTask;
    const savedTask = await TaskManager.addTask(taskData);
    setTasks([savedTask, ...tasks]);

    // Refresh from cloud to ensure consistent format
    try {
      const cloudTasks = await TaskManager.syncWithCloud();
      setTasks(cloudTasks);
    } catch (error) {
      console.error('Failed to refresh tasks from cloud:', error);
    }
  };

  const deleteTask = (id: number) => {
    Alert.alert(
      "Delete Task",
      "Are you sure you want to delete this note?",
      [
        { text: "Cancel", style: "cancel" },
        { 
          text: "Delete", 
          style: "destructive",
          onPress: async () => {
            setTasks(tasks.filter(t => t.id !== id));
            await TaskManager.deleteTask(id);
          }
        }
      ]
    );
  };

  const editTask = async (editedTask: Task) => {
    setTasks(tasks.map(t => t.id === editedTask.id ? editedTask : t));
    await TaskManager.updateTask(editedTask);
  };

  const addLocation = (location: Omit<SavedLocation, 'id'>) => {
    const newLocation = { ...location, id: Date.now().toString() };
    setSavedLocations([...savedLocations, newLocation]);
  };

  const updateLocation = (location: SavedLocation) => {
    setSavedLocations(savedLocations.map(loc => loc.id === location.id ? location : loc));
  };

  // Initialize notification listener on app start
  useEffect(() => {
    const initNotifications = async () => {
      try {
        console.log('[App] Initializing notification listener...');
        const success = await NotificationListener.initialize();
        console.log('[App] Notification listener init result:', success);
      } catch (error) {
        console.error('[App] Failed to initialize notification listener:', error);
      }
    };
    
    initNotifications();
  }, []);

  const renderPage = () => {
    switch (currentPage) {
      case 'home':
        return <HomePage 
          onNavigate={(page) => setCurrentPage(page)} 
          tasks={tasks}
          onToggleTask={toggleTask}
          onDeleteTask={deleteTask}
          onEditTask={editTask}
        />;
      case 'chat':
        return <ChatBoxPage />;
      case 'tasks':
        return <TasksPage 
          tasks={tasks}
          savedLocations={savedLocations}
          onToggleTask={toggleTask}
          onAddTask={addTask}
          onDeleteTask={deleteTask}
          onEditTask={editTask}
        />;
      case 'locations':
        return <LocationsPage 
          tasks={tasks}
          savedLocations={savedLocations}
          onAddLocation={addLocation}
          onUpdateLocation={updateLocation}
        />;
      case 'settings':
        return <SettingsPage />;
      default:
        return <HomePage 
          onNavigate={(page) => setCurrentPage(page)} 
          tasks={tasks}
          onToggleTask={toggleTask}
          onDeleteTask={deleteTask}
          onEditTask={editTask}
        />;
    }
  };

  return (
    <SafeAreaProvider>
      <LinearGradient
        colors={['#eff6ff', '#f5f3ff', '#fdf2f8']} // blue-50, purple-50, pink-50
        style={styles.container}
      >
        <SafeAreaView style={styles.safeArea} edges={['top', 'left', 'right']}>
          <StatusBar barStyle="dark-content" />
          
          {/* Page content */}
          <View style={styles.content}>
            {renderPage()}
          </View>
          
          {/* Bottom navbar */}
          <Navbar currentPage={currentPage} onPageChange={setCurrentPage} />

          {/* Dev Console Button */}
          <TouchableOpacity
            style={styles.devButton}
            onPress={() => setIsDevConsoleOpen(true)}
          >
            <Terminal size={24} color="#fff" />
          </TouchableOpacity>

          <DevConsoleModal
            visible={isDevConsoleOpen}
            onClose={() => setIsDevConsoleOpen(false)}
          />
        </SafeAreaView>
      </LinearGradient>
    </SafeAreaProvider>
  );
}

// Wrap the app in an ErrorBoundary to catch any errors and prevent crashes
export default function App() {
  return (
    <ErrorBoundary>
      <AppContent />
    </ErrorBoundary>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  content: {
    flex: 1,
    overflow: 'hidden',
  },
  devButton: {
    position: 'absolute',
    bottom: 100,
    right: 20,
    backgroundColor: '#333',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 1000,
  },
});
